name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install xmllint
      run: sudo apt-get install -y libasound2-dev libpulse-dev # libpipewire-0.3-dev libjack-jackd2-dev

    - name: Build
      run: cargo build --verbose
      
    #- name: Run tests TODO: make some tests?
    #  run: cargo test --verbose
